DROP DATABASE IF EXISTS weatherbot;

CREATE DATABASE weatherbot;

USE weatherbot;

DROP DATABASE IF EXISTS weatherbot;

CREATE DATABASE weatherbot;

USE weatherbot;

CREATE TABLE IF NOT EXISTS UserTable (userId INTEGER PRIMARY KEY, status INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS UserLanguage (userId INTEGER PRIMARY KEY, languageCode VARCHAR(10) NOT NULL);

CREATE TABLE IF NOT EXISTS WeatherSubscribe (userId INTEGER NOT NULL, subscribeWarning BOOLEAN NOT NULL DEFAULT FALSE, subscribeCurrentWeather BOOLEAN NOT NULL DEFAULT FALSE);
